apiVersion: v1
kind: Service
metadata:
  name: diabetes-ui
  labels:
    app: diabetes-ui
    component: inference-ui
spec:
  type: NodePort
  selector:
    app: diabetes-ui
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30085
    protocol: TCP
    name: http

