name: Deploy ðŸš€
on:
    push:
        branches: [ main ]

jobs:
    build:
        name: Build and Push the images
        runs-on: ubuntu-latest
        environment: env

        strategy:
            matrix:
                components: [ airflow ]
        env:
            DOCKERHUB_USERNAME: "germanaoq"
        steps:
            - uses: actions/checkout@v6
            - name: Print files
              run: ls
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ env.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Proyectos/Proyecto_final/${{ matrix.components }}/Dockerfile
                push: true
                tags: ${{ env.DOCKERHUB_USERNAME }}/mlops-${{ matrix.components }}:${{ github.sha }}
