apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  labels:
    app: mlflow
data:
  db_host: "postgresql-service.default.svc.cluster.local"
  db_port: "5432"
  db_name: "mlflow"
  db_user: "mlflow"
  db_password: "mlflowpass"
